# Generated by Django 2.1.2 on 2018-11-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(auto_created=True, max_length=10, verbose_name='부서코드'),
        ),
    ]
