# Generated by Django 2.1.2 on 2018-11-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_name', models.CharField(max_length=50, unique=True, verbose_name='상품명')),
                ('prod_code', models.AutoField(primary_key=True, serialize=False, verbose_name='상품코드')),
                ('prod_act', models.BooleanField(verbose_name='사용여부')),
                ('prod_memo', models.TextField(blank=True, null=True, verbose_name='상품메모')),
            ],
            options={
                'verbose_name_plural': '상품',
            },
        ),
    ]
